service: score
plugins:
  - serverless-dotenv-plugin

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  profile: bp-sls
  lambdaHashingVersion: 20201221
  environment:
    NODE_URL: ${env:NODE_URL}
    SERVERLESS: ${env:SERVERLESS}
  iam:
    role:
      statements: # permissions for all of your functions can be set here
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables in a specific region
            - s3:*
          Resource: '*'

functions:
  calc:
    handler: handler.calcScore
    timeout: 900 # optional, in seconds, default is 6 max is 15minutes  
    events:
      - schedule: rate(1 day)


